=== CamPr0ngs/ordinario-ftw/heroes.dtd
<!ELEMENT lista_heroes (heroe+)>
<!ELEMENT heroe (nombre, rol, habilidad, ultimate,  afiliacion, descripcion, tipoDuelista, tipoVanguardia, tipoEstratega, imagen)>
<!ATTLIST heroe id ID #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT rol (#PCDATA)>
<!ELEMENT habilidad (#PCDATA)>
<!ELEMENT ultimate (#PCDATA)>
<!ELEMENT afiliacion (#PCDATA)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT tipoDuelista (#PCDATA)>
<!ELEMENT tipoVanguardia (#PCDATA)>
<!ELEMENT tipoEstratega (#PCDATA)>
<!ELEMENT imagen (#PCDATA)>

=== CamPr0ngs/ordinario-ftw/heroes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lista_heroes SYSTEM "heroes.dtd">
<lista_heroes>
    <heroe id="H001">
        <nombre>Doctor Strange</nombre>
        <rol>Vanguardia</rol>
        <habilidad>Escudo de los Serafíns</habilidad>
        <ultimate>Ojo de Agamotto</ultimate>
        <afiliacion>Avengers</afiliacion>
        <descripcion>El Hechicero Supremo que abre portales, manipula el tiempo y protege a su equipo para asegurar la victoria.</descripcion>
        <imagen>img/Strange.png</imagen>
    </heroe>
    <heroe id="H002">
        <nombre>Hela</nombre>
        <rol>Duelista</rol>
        <habilidad>Espadas Nocturnas</habilidad>
        <ultimate>Diosa de la Muerte</ultimate>        
        <afiliacion>Asgard</afiliacion>
        <descripcion>La Diosa de la Muerte, lanza ráfagas de espadas nocturnas altamente precisas para acabar con sus rivales.</descripcion>
        <imagen>img/Hela.png</imagen>
    </heroe>
    <heroe id="H003">
        <nombre>Peni Parker</nombre>
        <rol>Vanguardia</rol>
        <habilidad>Trampas Arácnidas</habilidad>
        <ultimate>Barrido de Arañas</ultimate>
        <afiliacion>Spider-Verse</afiliacion>
        <descripcion>Pilota su poderoso traje SP//dr para colocar trampas de nido aránido y realentizar el avance enemigo, a la vez que les hace daño.</descripcion>
        <imagen>img/Peni.png</imagen>
    </heroe>
    <heroe id="H004">
        <nombre>Gambito</nombre>
        <rol>Estratega</rol>
        <habilidad>Cartas cinéticas</habilidad>
        <ultimate>Escalera Real Furiosa</ultimate>
        <afiliacion>X-Men</afiliacion>
        <descripcion>El carismático mutante que carga objetos con energía cinética, lanzando ráfagas de cartas explosivas para infligir gran daño a distancia y curar a sus aliados.</descripcion>
        <imagen>img/Gambito.png</imagen>
    </heroe>
</lista_heroes>
